version: 2

build:
  os: ubuntu-22.04 # https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995
  tools:
    python: '3.11'
  commands:
    - pip install poetry
    - poetry install
    - poetry run mkdocs build -f docs/mkdocs.yml -s -d $READTHEDOCS_OUTPUT/html