[build-system]
requires = ["setuptools>=67.7", "wheel"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["tastytrade_sdk*"]
exclude = ["tests*"]

[project]
name = "tastytrade-sdk"
version = "0.0.1"
authors = [
    { name = "Aaron Mamparo", email = "aaronmamparo@gmail.com" },
]
description = "A python wrapper around the tastytrade open API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/amamparo/tastytrade-sdk-python"
