site_name: tastytrade-sdk-python

docs_dir: markdown

theme:
    name: readthedocs

nav:
    - index.md
    - tastytrade.md
    - market_data.md
    - api.md

watch:
    - ../src

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
            heading_level: 3
            members_order: source
            show_if_no_docstring: true
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_bases: false
            allow_inspection: true
            group_by_category: false
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            docstring_section_style: list
            filters: ["!^_"]
