name: Dev Build
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Dev Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: make lint
      - run: make test
        env:
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          TASTYTRADE_LOGIN: ${{ secrets.TASTYTRADE_LOGIN }}
          TASTYTRADE_PASSWORD: ${{ secrets.TASTYTRADE_PASSWORD }}
      - name: Publish snapshot
        run: |
          poetry version "$(poetry version -s)dev${GITHUB_RUN_NUMBER}"
          poetry publish --build \
            -u ${{ secrets.PYPI_USERNAME }} \
            -p ${{ secrets.PYPI_PASSWORD }}