name: Dev CI
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - run: make test
      - name: Publish dev
        run: |
          poetry version "$(poetry version -s)dev${GITHUB_RUN_NUMBER}"
          poetry publish --build \
            -u ${{ secrets.PYPI_USERNAME }} \
            -p ${{ secrets.PYPI_PASSWORD }}