name: Release
concurrency:
  group: tastytrade-sdk-python-release
  cancel-in-progress: true
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - name: Publish
        run: |
          poetry publish --build \
            -u ${{ secrets.PYPI_USERNAME }} \
            -p ${{ secrets.PYPI_PASSWORD }}