name: Deploy
concurrency:
  group: tastytrade-sdk-python
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Upload
        run: |
          DEV_TAG="${GITHUB_RUN_NUMBER}" make set_dev_version_tag
          PYPI_USERNAME="${{ secrets.TEST_PYPI_USERNAME }}" \
          PYPI_PASSWORD="${{ secrets.TEST_PYPI_PASSWORD }}" \
          make build_upload