name: Deploy
concurrency:
  group: tastytrade-sdk-python
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install
      - name: Upload
        run: |
          poetry version "$(poetry version -s)dev${GITHUB_RUN_NUMBER}"
          poetry publish --build -r testpypi \
            -u ${{ secrets.TEST_PYPI_USERNAME }} \
            -p ${{ secrets.TEST_PYPI_PASSWORD }} \